ERROR 2025-09-17 14:09:56,144 views 10960 36080 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:09:56,146 views 10960 36080 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:09:56,146 views 10960 36080 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:09:56,148 views 10960 36080 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:09:56,149 views 10960 36080 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:09:56,149 views 10960 36080 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4B06AD0>.
ERROR 2025-09-17 14:10:09,783 views 10960 35164 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:10:09,784 views 10960 35164 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:10:09,785 views 10960 35164 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:10:09,786 views 10960 35164 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:10:09,787 views 10960 35164 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:10:09,789 views 10960 35164 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000001C1A4C91BD0>.
ERROR 2025-09-17 14:11:26,620 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:11:26,624 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:11:26,626 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:11:26,628 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:11:26,630 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:11:26,631 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395D19CC40>.
ERROR 2025-09-17 14:12:02,591 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:02,597 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:02,604 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:02,618 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:02,626 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:02,632 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2B60>.
ERROR 2025-09-17 14:12:13,845 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:13,846 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:13,848 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:13,849 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:13,850 views 27812 6892 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:13,851 views 27812 6892 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF1AE0>.
ERROR 2025-09-17 14:12:31,578 views 27812 30620 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
ERROR 2025-09-17 14:12:31,579 views 27812 30620 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
ERROR 2025-09-17 14:12:31,580 views 27812 30620 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
ERROR 2025-09-17 14:12:31,583 views 27812 30620 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
ERROR 2025-09-17 14:12:31,584 views 27812 30620 Error in UserMovieRatingDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
ERROR 2025-09-17 14:12:31,585 views 27812 30620 Error in UserMovieWatchlistDetailView.get_queryset: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x000002395CFF2AD0>.
